routes/web.php
<?php


Route::get('/FAQ', function(){return view('FAQ');})->name('FAQ');

Route::get('/logout',function(){
    Auth::logout();
    return redirect('/login');})->name('home.loguot');

Route::get('/login',function(){return "555";})->name('login');

Route::get('/done', function(){return 'done';})->name('status.done');

Route::get('/', function () {return view('welcome');})->name('home');

Auth::routes();


Route::get('/index', ['as' => 'index','uses' => 'metronicController@index']);


Route::namespace('Admin')->prefix('admin')->middleware('admin')->name('admin.')->group(
    function () {
        Route::namespace('body')->prefix('body')->name('body.')->group(
            function () {
                Route::get('/body/delete',['as' => 'body.delete','uses' => 'bodyController@destroy']);

                Route::get('/chest_abdomen_infection/delete',['as' => 'chest_abdomen_infection.delete','uses' => 'chest_abdomen_infectionsController@destroy']);

                Route::get('/head_infections/delete',['as' => 'head_infections.delete','uses' => 'head_infectionsController@destroy']);

                Route::get('/upper_limbs_infections/delete',['as' => 'upper_limbs_infections.delete','uses' => 'upper_limbs_infectionsController@destroy']);

                Route::get('/lower_limbs_infections/delete',['as' => 'lower_limbs_infections.delete','uses' => 'lower_limbs_infectionsController@destroy']);

                Route::resource('/body', 'bodyController');

                Route::resource('/head_infections', 'head_infectionsController');

                Route::resource('/chest_abdomen_infections', 'chest_abdomen_infectionsController');

                Route::resource('/upper_limbs_infections', 'upper_limbs_infectionsController');

                Route::resource('/lower_limbs_infections', 'lower_limbs_infectionsController');
            });


        Route::prefix('senders')->name('senders.')->group(
            function () {
                Route::get('/', ['as' => 'index', 'uses' => 'SendersController@index']);
                Route::get('/create', ['as' => 'create', 'uses' => 'SendersController@create']);
                Route::get('/show', ['as' => 'show', 'uses' => 'SendersController@show']);
                Route::get('/edit/{id}', ['as' => 'edit', 'uses' => 'SendersController@edit']);

                Route::get('/delete', ['as' => 'delete', 'uses' => 'SendersController@destroy']);
                Route::post('/sotre', ['as' => 'store', 'uses' => 'SendersController@store']);
                Route::put('/update/{id}', ['as' => 'update', 'uses' => 'SendersController@update']);
            });


        Route::prefix('Receptions')->name('Receptions.')->group(
            function(){
                Route::get('/', ['as' => 'index', 'uses' => 'ReceptionsController@index']);
                Route::get('/create', ['as' => 'create', 'uses' => 'ReceptionsController@create']);
                Route::get('/show', ['as' => 'show', 'uses' => 'ReceptionsController@show']);
                Route::get('/edit/{id}', ['as' => 'edit', 'uses' => 'ReceptionsController@edit']);
                Route::get('/delete', ['as' => 'delete', 'uses' => 'ReceptionsController@destroy']);
                Route::post('/sotre', ['as' => 'store', 'uses' => 'ReceptionsController@store']);
                Route::put('/update/{id}', ['as' => 'update', 'uses' => 'ReceptionsController@update']);
            });


        Route::prefix('ambulances')->name('ambulances.')->group(
            function(){
                Route::get('/', ['as' => 'index', 'uses' => 'AmbulancesController@index']);
                Route::get('/create', ['as' => 'create', 'uses' => 'AmbulancesController@create']);
                Route::get('/show', ['as' => 'show', 'uses' => 'AmbulancesController@show']);
                Route::get('/edit/{id}', ['as' => 'edit', 'uses' => 'AmbulancesController@edit']);
                Route::get('/delete', ['as' => 'delete', 'uses' => 'AmbulancesController@destroy']);
                Route::post('/sotre', ['as' => 'store', 'uses' => 'AmbulancesController@store']);
                Route::put('/update/{id}', ['as' => 'update', 'uses' => 'AmbulancesController@update']);
        });

                Route::get('convert/printpdf/{id}', ['as' => 'convert.printpdf', 'uses' => 'statusesController@printPDF']);
                Route::get('/statuses/ReadNote/{id}', ['as' => 'statuses.ReadNote', 'uses' => 'statusesController@ReadNote']);
                Route::get('/statuses/view-injuers/{id}', ['as' => 'statuses.view-injuers', 'uses' => 'statusesController@view_injuers']);
                Route::get('/statuses/view-bag/{id}', ['as' => 'statuses.view-Bags', 'uses' => 'statusesController@view_Bags']);
                // Route::get('/statuses/show',	['as' => 'statuses.showData', 'uses' => 'statusesController@show']);
                Route::resource('/statuses', 'statusesController');
                Route::resource('/profile', 'profileController');


        Route::namespace('bags')->prefix('bags/')->name('bags.')->group(
            function () {
                Route::get('/bags/delete',['as' => 'bags.delete','uses' => 'bagsController@destroy']);

                Route::get('/bags/influence_categories/delete',['as' => 'influence_categories.delete','uses' => 'influence_categoriesController@destroy']);

                Route::get('/bags/injection_categories/delete',['as' => 'injection_categories.delete','uses' => 'injection_categoriesController@destroy']);

                Route::resource('/bags', 'bagsController');
                Route::resource('/influence_categories', 'influence_categoriesController');
                Route::resource('/injection_categories', 'injection_categoriesController');
            });


    });


            Route::get('/admin/logout', function(){
                Auth::logout();
                return redirect('/login');})->name('admin.logout');


Route::namespace('Reception')->prefix('reception')->middleware('admin')->name('reception.')->group(
    function () {
        Route::prefix('test')->name('test.')->group(
            function () {
                Route::get('/', ['as' => 'index', 'uses' => 'TestController@index']);
                Route::get('/create', ['as' => 'create', 'uses' => 'TestController@create']);
                Route::post('/sotre', ['as' => 'store', 'uses' => 'TestController@store']);
            });


        Route::name('statuses.')->group(
            function () {
            Route::get('/statuses/ReadNote/{id}', ['as' => 'ReadNote', 'uses' => 'statusesController@ReadNote']);
            Route::resource('/report', 'reportController');
            Route::get('/statuses/view-injuers/{id}', ['as' => 'view-injuers', 'uses' => 'statusesController@view_injuers']);
            Route::get('/statuses/view-bag/{id}', ['as' => 'view-Bags', 'uses' => 'statusesController@view_Bags']);
        });
        Route::resource('/statuses', 'statusesController');
        Route::resource('/profile', 'profileController');
    });

Route::get('DIS/PDF',function (){
    return view('DIS_PDF');
});

app/bag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class bag extends Model
{
    protected $table = 'bags';
    protected $fillable = [
        'name',
    ];

}

app/bags.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class bags extends Model
{
    protected $table = 'bags';
    protected $fillable = [
        'name',
    ];

}

app/injection_category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class injection_category extends Model
{
    
    protected $table = 'injection_categories';
    protected $fillable = [
        'name','injection_id',
    ];
    
}

app/Http/Controllers/API/BagController.php
<?php

namespace App\Http\Controllers\API;

use App\bag;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BagController extends Controller
{
    public function index(){
        $bag = bag::all();
        $name = "Bag";
        return parent::success($name,$bag);
    }

    public function show($id){
        try{
            $bag = bag::findOrFail($id);
            $name = "Bag";
            return parent::success($name , $bag);
        }catch (ModelNotFoundException $modelNotFoundException){
            return parent::error("The content Bag not found");
        }
    }


}

app/Http/Controllers/API/bag/influenceController.php
<?php

namespace App\Http\Controllers\API\bag;

use App\influence_category;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class influenceController extends Controller
{
    public function index(){
        $influence = influence_category::all();
        $name = "influence";
        return parent::success($name , $influence);
    }

    public function show($id){
        try{
        $influence = influence_category::findOrFail($id);
        return parent::success($influence);
        }catch (ModelNotFoundException $modelNotFoundException){
            return parent::error("influence is not found");
        }
    }
}

app/Http/Controllers/API/bag/injectionController.php
<?php

namespace App\Http\Controllers\API\bag;

use App\injection_category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class injectionController extends Controller
{
    public function index(){
        $injection = injection_category::all();
        $name = "injection";
        return parent::success($name , $injection);
    }

    public function show($id){
        try{
            $injection = injection_category::findOrFail($id);
            return parent::success($injection);
        }catch (ModelNotFoundException $modelNotFoundException){
            return parent::error("injection is not found");
        }
    }
}

app/Http/Controllers/Admin/bags/bagsController.php
<?php

namespace App\Http\Controllers\Admin\bags;

use App\Custom_Triates\bags\R_M_bags;
use App\bag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Database\QueryException;

class bagsController extends Controller
{
    use R_M_bags;

   
    public function index(){

        $request = request();
        $name = $request->name;
        $bags = bag::when($name, function ($query, $name) {
             $query->where('name', 'LIKE', '%' . $name . '%');
         })->latest()->get();
        

        // $bags = bag::all();
        return view('admin.bags.bags.index',[
            'bags' => $bags,
            'name' => $name
        ]);
    }

    public function create(){

        return view('admin.bags.bags.create');
    }


    public function store(Request $request)
    {
        $request->validate($this->rules(), $this->messages());
        $bags =  bag::create([
            'name' => $request['name'],
        ]);
        return redirect()->route('admin.bags.bags.index');
    }



    

    public function edit($id)
    {
        $bags= bag::findorFail($id);



        return view('Admin.bags.bags.edit',[
            'bags' => $bags,
        ]);

    }


    
    public function update(Request $request, $id)
    {
        $bags = bag::findorFail($id);
        $request->validate($this->rules(), $this->messages());
        $bags->update([
            'name' => $request['name'],
        ]);
        return redirect()->route('admin.bags.bags.index');
    }


    

    public function destroy()
    {

        try{
            // هنا علشان ممنوع يحذف الابو وفيه له ابناء
            $request = request();
            $bag_id = $request->bag_id;
            bag::findorFail($bag_id)->delete();
        }catch(QueryException $e){
        return response()->json([
            'success' => 'can\'t delete this item',
        ]);    
        }
        return response()->json([
            'success' => 2,
          
        ]);

    }










}

app/Http/Controllers/Admin/bags/influence_categoriesController.php
<?php

namespace App\Http\Controllers\Admin\bags;

use App\bag;
use App\Custom_Triates\bags\R_M_influence_categories;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\influence_category;
use Illuminate\Database\QueryException;

class influence_categoriesController extends Controller
{
    
    use R_M_influence_categories;

   
    public function index(){


        $request = request();
        $name = $request->name;
        $influence_categories = influence_category::when($name, function ($query, $name) {
             $query->where('name', 'LIKE', '%' . $name . '%');
         })->latest()->get();
        

        // $influence_categories = influence_category::all();
        return view('admin.bags.influence_categories.index',[
            'influence_categories' => $influence_categories,
            'name' => $name
        ]);
    }

    
    public function create()
    {

        return view('admin.bags.influence_categories.create',[
            'bag' => bag::all(),
        ]);
    }

    
    public function store(Request $request)
    {
        $request->validate($this->rules(), $this->messages());

        // $influence_categorie =  bag::where('name', '=', 'influence')->first();
        // $influence_categorie_id = 0;
        // if ($influence_categorie) {
        //     $influence_categorie_id = $influence_categorie->id;
        // }
        $influence_categorie =  influence_category::create([
            'name' => $request['name'],
            'influence_id' => $request->influence_categorie_id
        ]);
        return redirect()->route('admin.bags.influence_categories.index');
    }


    
    
    public function edit($id)
    {
        $influence_category = influence_category::findorFail($id);



        return view('admin.bags.influence_categories.edit', [
            'influence_category' => $influence_category,
            'bag' => bag::all(),

        ]);
    }



    public function update(Request $request, $id)
    {

        $influence_category = influence_category::findorFail($id);
        $request->validate($this->rules(), $this->messages());
        $influence_category->update([
            'name' => $request['name'],
            'influence_id' => $request->influence_categorie_id

        ]);
        return redirect()->route('admin.bags.influence_categories.index');
        
    }



    
    
    public function destroy()
    {

        try{
            // هنا علشان ممنوع يحذف الابو وفيه له ابناء
            $request = request();
            $influence_category_id = $request->influence_category_id;
            influence_category::findorFail($influence_category_id)->delete();
        }catch(QueryException $e){
        return response()->json([
            'success' => 'can\'t delete this item',
        ]);    
        }
        return response()->json([
            'success' => 2,
          
        ]);

    }







}

app/Http/Controllers/Admin/bags/injection_categoriesController.php
<?php

namespace App\Http\Controllers\Admin\bags;

use App\bag;
use App\Custom_Triates\bags\R_M_injection_categories;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\injection_category;

class injection_categoriesController extends Controller
{
  use R_M_injection_categories;

   
  public function index(){



    $request = request();
    $name = $request->name;
    $injection_categories = injection_category::when($name, function ($query, $name) {
         $query->where('name', 'LIKE', '%' . $name . '%');
     })->latest()->get();
    


    //   $injection_categories = injection_category::all();
      return view('admin.bags.injection_categories.index',[
          'injection_categories' => $injection_categories,
          'name' => $name,
      ]);
  }


      
  public function create()
  {

      return view('admin.bags.injection_categories.create',[
          'bag' => bag::all(),
      ]);
  }


  
  public function store(Request $request)
  {
      $request->validate($this->rules(), $this->messages());

    //   $item =  bag::where('name', '=', 'injection')->first();
    //   $item_id = 0;
    //   if ($item) {
    //       $item_id = $item->id;
    //   }
      injection_category::create([
          'name' => $request['name'],
          'injection_id' => $request->injection_id
      ]);
      return redirect()->route('admin.bags.injection_categories.index');
  }


  
  public function edit($id)
  {
      $injection_category = injection_category::findorFail($id);



      return view('admin.bags.injection_categories.edit', [
          'injection_category' => $injection_category,
          'bag' => bag::all(),

      ]);
  }



  
  public function update(Request $request, $id)
  {

      $item = injection_category::findorFail($id);
      $request->validate($this->rules(), $this->messages());
      $item->update([
          'name' => $request['name'],
          'injection_id' => $request->injection_id

      ]);
      return redirect()->route('admin.bags.injection_categories.index');
      
  }



  



  public function destroy()
  {

      try{
          // هنا علشان ممنوع يحذف الابو وفيه له ابناء
          $request = request();
          $injection_category_id = $request->injection_category_id;
          injection_category::findorFail($injection_category_id)->delete();
      }catch(QueryException $e){
      return response()->json([
          'success' => 'can\'t delete this item',
      ]);    
      }
      return response()->json([
          'success' => 2,
        
      ]);

  }



  

}

resources/views/admin/bags/injection_categories/create.blade.php
@extends('base_layout.master_layout')
@section('title','create influence_categorie')
@section('style')
<style>

</style>
@endsection

@section('body')


<div class="row">
  <div class="col-lg-12">

    <!--begin::Portlet-->
    <div class="m-portlet">


      <!--begin::Form-->
      <form method="post" action="{{route('admin.bags.injection_categories.store')}}" class="m-form m-form--label-align-right">
        @csrf
        <div class="m-portlet__body">
          <div class="m-form__section m-form__section--first">
            <div class="m-form__heading">
              <h3 class="m-form__heading-title">New injection_categorie:</h3>
            </div>

            <div class="form-group m-form__group row">
              <label for="name" class="col-lg-2 col-form-label">Name:</label>
              <div class="col-lg-6">
                <input value="{{old('name')}}" id="name" name="name" type="text" class="form-control m-input" placeholder="Enter name" autofocus>
                <span class="m-form__help red"> {{$errors->first('name')}} </span>


              </div>
            </div>




            <div class="form-group m-form__group row">
                <label for="injection_id" class="col-lg-2 col-form-label">body:</label>
  
                <div class="col-lg-6">
         
                    <select 
                    class="form-control m-input m-input--square"
                     id="injection_id"
                      name="injection_id">
  
                        <option value="-1" disabled selected>choose body</option>
                        @foreach ($bag as $item)
                    <option  value="{{$item->id}}" {{old('injection_id')== $item->id? 'selected':''}} >{{$item->name}}</option>
                            
                        @endforeach
                      </select>
  
                  <span class="m-form__help red"> {{$errors->first('injection_id')}} </span>
  
  
                </div>
              </div>










          </div>


        </div>
        <div class="m-portlet__foot m-portlet__foot--fit">
          <div class="m-form__actions m-form__actions">
            <div class="row">
              <div class="col-lg-2"></div>
              <div class="col-lg-6">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="{{route('admin.bags.injection_categories.index')}}" class="btn btn-secondary">Cancel</a>
              </div>
            </div>
          </div>
        </div>
      </form>

      <!--end::Form-->
    </div>

  </div>
</div>

@endsection

@section('script')
<script src="{{asset('default/assets/demo/default/custom/crud/forms/widgets/bootstrap-datepicker.js')}}" type="text/javascript"></script>

@endsection

resources/views/admin/bags/injection_categories/index.blade.php
@extends('base_layout.master_layout')
@section('title','injection_categories')

@section('style')
    <style>
    </style>
@endsection

@section('body')



    <!-- END: Left Aside -->
    <div class="m-grid__item m-grid__item--fluid m-wrapper">


        <!-- END: Subheader -->
        <div class="m-content">

            <div class="m-portlet m-portlet--mobile">


                <div class="m-portlet__body">

                      
                    
                    	<!--begin: Search Form -->
    <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
            <div class="row align-items-center">
                <div class="col-md-8">
                       
                        <form action="{{route('admin.bags.injection_categories.index')}}" method="get">
                            <div class="row">
                            <div class="col-md-5">
                                    <div class="m-input-icon m-input-icon--left">
                                          
                                            <input 
                                            autofocus
                                                     name="name"
                                                      value="{{$name}}"
                                                       type="text"
                                                        class="form-control m-input m-input--solid"
                                                         placeholder="Search by serial..."
                                                          id="generalSearch">

                                            <span class="m-input-icon__icon m-input-icon__icon--left">
                                                <span><i class="la la-search"></i></span>
                                            </span>
                                        </div>

                            </div>    
                            <div class="col-md-3">
                                
											<button type="submit" class="btn btn-primary">search</button>		
                                 
                                </div>    
                            
                            </div>    
                           
                            
                                    
                        </form>
                        
                     
                </div>
                <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                    <a href="{{route('admin.bags.injection_categories.create')}}" class="btn btn-accent m-btn m-btn--custom m-btn--icon m-btn--air m-btn--pill">
                        <span>
                            <i class="la la-cart-plus"></i>
                            <span>New injection category</span>
                            
                        </span>
                    </a>
                    <div class="m-separator m-separator--dashed d-xl-none"></div>
                </div>
            </div>
        </div>

        <!--end: Search Form -->
           


                    <!--begin: Datatable -->

                    <div class="m_datatable m-datatable m-datatable--default m-datatable--loaded" id="local_data"
                         style="">
                        <table class="m-datatable__table" style="display: block; min-height: 300px; overflow-x: auto;">
                            <thead class="m-datatable__head">
                            <tr class="m-datatable__row" style="left: 0px;">
                                <th data-field="ShipName" class="m-datatable__cell m-datatable__cell--sort">
                                    <span style="width: 110px;">#</span>
                                </th>

                                <th data-field="ShipName" class="m-datatable__cell m-datatable__cell--sort">
                                    <span style="width: 110px;">Name</span>
                                </th>


                                <th data-field="Type" class="m-datatable__cell m-datatable__cell--sort">
                                    <span style="width: 110px;">created_at</span>
                                </th>
                                <th data-field="Actions" class="m-datatable__cell m-datatable__cell--sort">
                                    <span style="width: 110px;">Actions</span>
                                </th>
                            </tr>
                            </thead>

                            <tbody class="m-datatable__body" style="">


                            @foreach($injection_categories as $injection_categorie)
                                <tr data-row="0" class="m-datatable__row" style="left: 0px;">


                                    <td data-field="ShipName" class="m-datatable__cell">
                                        <span style="width: 110px;"> {{$injection_categorie->id}} </span>
                                    </td>


                                    <td data-field="Currency" class="m-datatable__cell">
                                        <span style="width: 100px;">{{$injection_categorie->name}}</span>
                                    </td>


                                    <td data-field="Latitude" class="m-datatable__cell"><span
                                                style="width: 110px;">{{$injection_categorie->created_at->diffForHumans()}}</span>
                                    </td>


                                    <td data-field="Actions" class="m-datatable__cell">
									<span style="overflow: visible; position: relative; width: 110px;">
										<div class="dropdown ">
											<a href="#"
                                               class="btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill"
                                               data-toggle="dropdown">
												<i class="la la-ellipsis-h"></i>
											</a>
											<div class="dropdown-menu dropdown-menu-right">
										<!-- <button type="submit" class="btn btn-link">Delete</button> -->


										<a class="dropdown-item"
                                           href="{{ route('admin.bags.injection_categories.edit',$injection_categorie->id) }}">
													<i class="la la-edit"></i> Edit</a>


		
																										
													<a class="dropdown-item delete-btn"
                                                       data-id='{{$injection_categorie->id}}'
                                                       href="#">
										<i class="la la-trash"></i> Delete
								</a>



												
											</div>
										</div>
										<a class='view-ambulance' data-id="{{ 5 }}" data-toggle="modal"
                                           data-target="#m_modal_ambulance" href="#"
                                           class="m-portlet__nav-link btn m-btn m-btn--hover-accent m-btn--icon m-btn--icon-only m-btn--pill"
                                           title="View ">
											<i class="la la-edit"></i>
										</a>


									</span>
                                    </td>
                                </tr>

                            @endforeach


                            <tbody>

                        </table>
                    </div>


                    <!--end: Datatable -->


                </div>
            </div>
        </div>
    </div>




    <!--begin::Modal-->
    <div class="modal fade" id="m_modal_ambulance" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">


                <div class="modal-body">
                    <div class="m-portlet__body">
                        <div class="m-form__section m-form__section--first">
                            <div class="m-form__heading">
                                <h3 class="m-form__heading-title">Ambulance Info:</h3>
                            </div>

                            <div class="form-group m-form__group row">
                                <label for="name" class="col-lg-2 col-form-label">Name:</label>
                                <div class="col-lg-6">
                                    <input disabled disabled id="Ambulance-Name" name="name" type="text"
                                           class="form-control m-input">
                                </div>
                            </div>


                        </div>


                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <!-- <button  data-dismiss="modal" type="button" class="btn btn-primary">Send message</button> -->
                </div>
            </div>
        </div>
    </div>

    <!--end::Modal-->





@endsection

@section('script')
    <script src="{{asset('default/assets/demo/default/custom/crud/metronic-datatable/base/data-local.js')}}"
            type="text/javascript"></script>




    <script>
        var Ambulance_name = document.getElementById('Ambulance-Name');
        var user = document.querySelector('.view-ambulance');
        var modal = document.querySelector('#m_modal_ambulance');
        $('.view-ambulance').click(function (e) {
            modal.display = 'none';
            e.preventDefault();
            var id = $(this).data('id');
            console.log(id);


            $.get('{{ route('admin.ambulances.show')}}', {
                    ambulance_id: id,
                },
                function (data) {
                    Ambulance_name.value = data.ambulance_data.name;
                    modal.display = 'block';

                });


        });


        $('.delete-btn').click(function (e) {
            e.preventDefault();

            var id = $(this).data('id');

            $.get('{{route('admin.bags.injection_categories.delete')}}', {
                injection_category_id: id
            }, function (data) {
                console.log(data.success)
                window.location.reload();
            });

        });


    </script>

@endsection